# Generated by Django 4.1.2 on 2023-03-23 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myexpenses', '0002_alter_userexpenses_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexpenses',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL),
        ),
    ]
